export const BOOK_ABBR: Record<string, string> = {
  "Genesis": "Gen",
  "Exodus": "Exo",
  "Leviticus": "Lev",
  "Numbers": "Num",
  "Deuteronomy": "Deut",
  "Joshua": "Josh",
  "Judges": "Judg",
  "Ruth": "Ruth",
  "1 Samuel": "1 Sam",
  "First Samuel": "1 Sam",
  "2 Samuel": "2 Sam",
  "Second Samuel": "2 Sam",
  "1 Kings": "1 Kings",
  "First Kings": "1 Kings",
  "2 Kings": "2 Kings",
  "Second Kings": "2 Kings",
  "1 Chronicles": "1 Chron",
  "First Chronicles": "1 Chron",
  "2 Chronicles": "2 Chron",
  "Second Chronicles": "2 Chron",
  "Ezra": "Ezra",
  "Nehemiah": "Neh",
  "Esther": "Esth",
  "Job": "Job",
  "Psalms": "Psa",
  "Psalm": "Psa",
  "Proverbs": "Prov",
  "Ecclesiastes": "Eccl",
  "Song of Songs": "S.S.",
  "Song of Solomon": "S.S.",
  "Isaiah": "Isa",
  "Jeremiah": "Jer",
  "Lamentations": "Lam",
  "Ezekiel": "Ezek",
  "Daniel": "Dan",
  "Hosea": "Hosea",
  "Joel": "Joel",
  "Amos": "Amos",
  "Obadiah": "Obad",
  "Jonah": "Jonah",
  "Micah": "Micah",
  "Nahum": "Nahum",
  "Habakkuk": "Hab",
  "Zephaniah": "Zeph",
  "Haggai": "Hag",
  "Zechariah": "Zech",
  "Malachi": "Mal",
  "Matthew": "Matt",
  "Mark": "Mark",
  "Luke": "Luke",
  "John": "John",
  "Acts": "Acts",
  "Romans": "Rom",
  "1 Corinthians": "1 Cor",
  "First Corinthians": "1 Cor",
  "2 Corinthians": "2 Cor",
  "Second Corinthians": "2 Cor",
  "Galatians": "Gal",
  "Ephesians": "Eph",
  "Philippians": "Phil",
  "Colossians": "Col",
  "1 Thessalonians": "1 Thes",
  "First Thessalonians": "1 Thes",
  "2 Thessalonians": "2 Thes",
  "Second Thessalonians": "2 Thes",
  "1 Timothy": "1 Tim",
  "First Timothy": "1 Tim",
  "2 Timothy": "2 Tim",
  "Second Timothy": "2 Tim",
  "Titus": "Titus",
  "Philemon": "Philem",
  "Hebrews": "Heb",
  "James": "James",
  "1 Peter": "1 Pet",
  "First Peter": "1 Pet",
  "2 Peter": "2 Pet",
  "Second Peter": "2 Pet",
  "1 John": "1 John",
  "First John": "1 John",
  "2 John": "2 John",
  "Second John": "2 John",
  "3 John": "3 John",
  "Third John": "3 John",
  "Jude": "Jude",
  "Revelation": "Rev"
};

export const ALL_BOOK_TOKENS = (() => {
  const set = new Set<string>();
  for (const [k, v] of Object.entries(BOOK_ABBR)) { set.add(k); set.add(v); }
  return [...set].sort((a, b) => b.length - a.length);
})();


/** Python-parity mapping for BibleHub interlinear slugs */
export const BIBLEHUB_INTERLINEAR: Record<string, string> = {
  "Gen": "genesis",
  "Exo": "exodus",
  "Lev": "leviticus",
  "Num": "numbers",
  "Deut": "deuteronomy",
  "Josh": "joshua",
  "Judg": "judges",
  "Ruth": "ruth",
  "1 Sam": "1_samuel",
  "2 Sam": "2_samuel",
  "1 Kings": "1_kings",
  "2 Kings": "2_kings",
  "1 Chron": "1_chronicles",
  "2 Chron": "2_chronicles",
  "Ezra": "ezra",
  "Neh": "nehemiah",
  "Esth": "esther",
  "Job": "job",
  "Psa": "psalms",
  "Prov": "proverbs",
  "Eccl": "ecclesiastes",
  "SoS": "songs", // Song of Solomon / Song of Songs
  "S.S.": "songs", // Song of Solomon / Song of Songs
  "Isa": "isaiah",
  "Jer": "jeremiah",
  "Lam": "lamentations",
  "Ezek": "ezekiel",
  "Dan": "daniel",
  "Hosea": "hosea",
  "Joel": "joel",
  "Amos": "amos",
  "Obad": "obadiah",
  "Jonah": "jonah",
  "Micah": "micah",
  "Nah": "nahum",
  "Hab": "habakkuk",
  "Zep": "zephaniah",
  "Zeph": "zephaniah",
  "Hag": "haggai",
  "Zech": "zechariah",
  "Mal": "malachi",
  "Matt": "matthew",
  "Mark": "mark",
  "Luke": "luke",
  "John": "john",
  "Acts": "acts",
  "Rom": "romans",
  "1 Cor": "1_corinthians",
  "2 Cor": "2_corinthians",
  "Gal": "galatians",
  "Eph": "ephesians",
  "Phil": "philippians",
  "Col": "colossians",
  "1 Thes": "1_thessalonians",
  "2 Thes": "2_thessalonians",
  "1 Tim": "1_timothy",
  "2 Tim": "2_timothy",
  "Titus": "titus",
  "Philem": "philemon",
  "Heb": "hebrews",
  "James": "james",
  "1 Pet": "1_peter",
  "2 Pet": "2_peter",
  "1 John": "1_john",
  "2 John": "2_john",
  "3 John": "3_john",
  "Jude": "jude",
  "Rev": "revelation"
}